replicaCount: 2
image:
  repository: bluezd/suse-demo-frontend
  pullPolicy: Always
  tag: a02d22d6def74bf1d52c7438161ddcde2f0ca347
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 8000
ingress:
  enabled: true
  annotations: {}
  hosts:
  - host: frontend.suse.demo
    paths:
    - /
  tls: []
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
